from setuptools import setup

setup(
    name='exercise-2-ffmpeg-mmark9',
    version='',
    packages=['venv.lib.python3.6.site-packages.py', 'venv.lib.python3.6.site-packages.py._io',
              'venv.lib.python3.6.site-packages.py._log', 'venv.lib.python3.6.site-packages.py._code',
              'venv.lib.python3.6.site-packages.py._path', 'venv.lib.python3.6.site-packages.py._process',
              'venv.lib.python3.6.site-packages.py._vendored_packages', 'venv.lib.python3.6.site-packages.attr',
              'venv.lib.python3.6.site-packages.mypy', 'venv.lib.python3.6.site-packages.mypy.test',
              'venv.lib.python3.6.site-packages.mypy.server', 'venv.lib.python3.6.site-packages.mypy.plugins',
              'venv.lib.python3.6.site-packages.mypy.newsemanal', 'venv.lib.python3.6.site-packages.flake8',
              'venv.lib.python3.6.site-packages.flake8.api', 'venv.lib.python3.6.site-packages.flake8.main',
              'venv.lib.python3.6.site-packages.flake8.options', 'venv.lib.python3.6.site-packages.flake8.plugins',
              'venv.lib.python3.6.site-packages.flake8.formatting', 'venv.lib.python3.6.site-packages.pluggy',
              'venv.lib.python3.6.site-packages._pytest', 'venv.lib.python3.6.site-packages._pytest._io',
              'venv.lib.python3.6.site-packages._pytest.mark', 'venv.lib.python3.6.site-packages._pytest._code',
              'venv.lib.python3.6.site-packages._pytest.config', 'venv.lib.python3.6.site-packages._pytest.assertion',
              'venv.lib.python3.6.site-packages.pyflakes', 'venv.lib.python3.6.site-packages.pyflakes.test',
              'venv.lib.python3.6.site-packages.pyflakes.scripts', 'venv.lib.python3.6.site-packages.typed_ast',
              'venv.lib.python3.6.site-packages.atomicwrites', 'venv.lib.python3.6.site-packages.more_itertools',
              'venv.lib.python3.6.site-packages.more_itertools.tests',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.idna',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pytoml',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.certifi',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet.cli',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.msgpack',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.util',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.req',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.vcs',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.utils',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.models',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.commands',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.operations'],
    url='',
    license='MIT',
    author='Miguel',
    author_email='mmark9@bu.edu',
    description='async hw'
)
